# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editorWindow(object):
    def setupUi(self, editorWindow):
        editorWindow.setObjectName("editorWindow")
        editorWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        editorWindow.resize(515, 350)
        self.centralwidget = QtWidgets.QWidget(editorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_newEntry = QtWidgets.QPushButton(self.centralwidget)
        self.btn_newEntry.setObjectName("btn_newEntry")
        self.horizontalLayout.addWidget(self.btn_newEntry)
        self.btn_deleteEntry = QtWidgets.QPushButton(self.centralwidget)
        self.btn_deleteEntry.setObjectName("btn_deleteEntry")
        self.horizontalLayout.addWidget(self.btn_deleteEntry)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnImport = QtWidgets.QPushButton(self.centralwidget)
        self.btnImport.setObjectName("btnImport")
        self.horizontalLayout_2.addWidget(self.btnImport)
        self.btnExport = QtWidgets.QPushButton(self.centralwidget)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_2.addWidget(self.btnExport)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tblEdit = QtWidgets.QTableWidget(self.centralwidget)
        self.tblEdit.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblEdit.setObjectName("tblEdit")
        self.tblEdit.setColumnCount(0)
        self.tblEdit.setRowCount(0)
        self.verticalLayout.addWidget(self.tblEdit)
        editorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(editorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 515, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setEnabled(True)
        self.menuFile.setObjectName("menuFile")
        editorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(editorWindow)
        self.statusbar.setObjectName("statusbar")
        editorWindow.setStatusBar(self.statusbar)
        self.act_save = QtWidgets.QAction(editorWindow)
        self.act_save.setObjectName("act_save")
        self.actionSave_as_Backup = QtWidgets.QAction(editorWindow)
        self.actionSave_as_Backup.setObjectName("actionSave_as_Backup")
        self.act_export = QtWidgets.QAction(editorWindow)
        self.act_export.setEnabled(True)
        self.act_export.setObjectName("act_export")
        self.act_close = QtWidgets.QAction(editorWindow)
        self.act_close.setObjectName("act_close")
        self.act_import = QtWidgets.QAction(editorWindow)
        self.act_import.setEnabled(True)
        self.act_import.setObjectName("act_import")
        self.menuFile.addAction(self.act_import)
        self.menuFile.addAction(self.act_export)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.act_save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.act_close)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(editorWindow)
        QtCore.QMetaObject.connectSlotsByName(editorWindow)

    def retranslateUi(self, editorWindow):
        _translate = QtCore.QCoreApplication.translate
        editorWindow.setWindowTitle(_translate("editorWindow", "Keyword Editor"))
        self.btn_newEntry.setText(_translate("editorWindow", "New Category"))
        self.btn_deleteEntry.setText(_translate("editorWindow", "Delete Category"))
        self.btn_save.setText(_translate("editorWindow", "Save Default and Close"))
        self.btnImport.setText(_translate("editorWindow", "Import CSV"))
        self.btnExport.setText(_translate("editorWindow", "Export CSV"))
        self.menuFile.setTitle(_translate("editorWindow", "File"))
        self.act_save.setText(_translate("editorWindow", "Save default"))
        self.actionSave_as_Backup.setText(_translate("editorWindow", "Save as (Backup)"))
        self.act_export.setText(_translate("editorWindow", "Export CSV"))
        self.act_close.setText(_translate("editorWindow", "Close"))
        self.act_import.setText(_translate("editorWindow", "Import CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editorWindow = QtWidgets.QMainWindow()
    ui = Ui_editorWindow()
    ui.setupUi(editorWindow)
    editorWindow.show()
    sys.exit(app.exec_())
