# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newItemWindow(object):
    def setupUi(self, newItemWindow):
        newItemWindow.setObjectName("newItemWindow")
        newItemWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        newItemWindow.resize(309, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(newItemWindow.sizePolicy().hasHeightForWidth())
        newItemWindow.setSizePolicy(sizePolicy)
        newItemWindow.setMinimumSize(QtCore.QSize(309, 150))
        newItemWindow.setMaximumSize(QtCore.QSize(309, 150))
        self.centralwidget = QtWidgets.QWidget(newItemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lblEntry = QtWidgets.QLabel(self.centralwidget)
        self.lblEntry.setObjectName("lblEntry")
        self.verticalLayout.addWidget(self.lblEntry)
        self.txtEntryName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEntryName.setMaxLength(60)
        self.txtEntryName.setObjectName("txtEntryName")
        self.verticalLayout.addWidget(self.txtEntryName)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout.addWidget(self.btnCreate)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        newItemWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(newItemWindow)
        QtCore.QMetaObject.connectSlotsByName(newItemWindow)

    def retranslateUi(self, newItemWindow):
        _translate = QtCore.QCoreApplication.translate
        newItemWindow.setWindowTitle(_translate("newItemWindow", "New Category"))
        self.lblEntry.setText(_translate("newItemWindow", "Category Name:"))
        self.btnCreate.setText(_translate("newItemWindow", "Create"))
        self.btnCancel.setText(_translate("newItemWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newItemWindow = QtWidgets.QMainWindow()
    ui = Ui_newItemWindow()
    ui.setupUi(newItemWindow)
    newItemWindow.show()
    sys.exit(app.exec_())
